[package]
name = "svg-optimizer"
version = "1.0.0"
edition = "2024"
description = "SVG file optimizer"
license = "MIT"
repository = "https://github.com/Pavi1on-Mk-Git/svg-optimizer"
keywords = ["svg", "optimizer"]
categories = ["command-line-utilities"]
include = ["/src"]

[lints.clippy]
match_wildcard_for_single_variants = "allow"
pedantic = { level = "warn", priority = -1 }

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.20", features = ["derive"] }
itertools = "0.14.0"
lazy-regex = "3.4.1"
nalgebra = "0.34.1"
rayon = "1.10.0"
xml-rs = "1.0.0"
